# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the trunk branch
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The destination repo'
        required: true
      filename:
        description: 'The filename to copy'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Copycat Action
        uses: andstor/copycat-action@v3.2.3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src_path: /workflow-templates/${{ github.event.inputs.filename }}
          dst_path: /.github/workflows/
          dst_owner: actionsdemo
          dst_repo_name: ${{ github.event.inputs.repo }}
          src_branch: trunk
          dst_branch: trunk

